# Generated by Django 2.2 on 2022-10-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('1', '初级'), ('2', '中级'), ('3', '高级')], max_length=1, verbose_name='难度'),
        ),
    ]
