# Generated by Django 2.2 on 2023-02-13 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20230209_1947'),
        ('courses', '0002_auto_20221023_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='所属机构'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_classic',
            field=models.BooleanField(default=False, verbose_name='是否为经典课程'),
        ),
    ]
