# Generated by Django 3.2.10 on 2022-10-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('1', '培训机构'), ('2', '个人'), ('3', '高校')], max_length=1, verbose_name='机构类别'),
        ),
    ]
