# Generated by Django 3.2.10 on 2022-10-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_courseorg_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='logo',
            field=models.ImageField(upload_to='CourseOrg/机构名称/', verbose_name='logo'),
        ),
    ]
